Add sumSalary
js-tasks-ru/jsbasic-20210520_golubmarian3 pull request #4
Opened 2021-05-31 13:17 UTC by golubmarian

2021-06-01 19:36 UTC, golubmarian commented
@koalex примите плз пул реквест.

2021-06-02 03:08 UTC, koalex approved these changes

2021-06-02 03:14 UTC, koalex approved these changes, later dismissed

2021-06-03 04:22 UTC, koalex approved these changes, later dismissed

2021-06-03 13:48 UTC, golubmarian reviewed
@koalex можно ли еще больше сократить код?

2021-06-04 01:38 UTC, koalex submitted a review, later dismissed

2021-06-08 16:55 UTC, golubmarian commented
@koalex нужна помощь. Сломал голову. Не могу понять почему тест не проходит. Подскажите плиз.

2021-06-09 10:19 UTC, koalex requested changes

2021-06-09 10:19 UTC, koalex commented on 4-module/3-task/index.js
> +      table.rows[i].cells[3].dataset.available == 'true' ? table.rows[i].className = 'available' : table.rows[i].className = 'unavailable';
Тут className перезаписывает все css-классы которые были раньше надо использовать classList:
замени на:
`table.rows[i].cells[3].dataset.available == 'true' ? table.rows[i].classList.add('available') : table.rows[i].classList.add('unavailable');`

2021-06-09 11:30 UTC, golubmarian commented on 4-module/3-task/index.js
> +      table.rows[i].cells[3].dataset.available == 'true' ? table.rows[i].className = 'available' : table.rows[i].className = 'unavailable';
Так там нет изначально классов в tr, поэтому я и взял className чтобы создать атрибут class. Или я что-то неверно понимаю?

2021-06-09 11:38 UTC, koalex commented on 4-module/3-task/index.js
> +      table.rows[i].cells[3].dataset.available == 'true' ? table.rows[i].className = 'available' : table.rows[i].className = 'unavailable';
В тестах [есть](https://github.com/golubmarian/jsbasic-20210520_golubmarian3/blob/master/4-module/3-task/task.test.js#L21)

2021-06-09 21:36 UTC, golubmarian commented on 4-module/3-task/index.js
> +      table.rows[i].cells[3].dataset.available == 'true' ? table.rows[i].className = 'available' : table.rows[i].className = 'unavailable';
спасибо! теперь все понятно

2021-06-10 09:58 UTC, koalex approved these changes

2021-06-10 10:08 UTC, merged